[package]
name = "accelerator"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
rglua = "3.0.0-beta2"
skidscan = "2.0.1"
toml = "0.7.5"
thiserror = "1.0"
anyhow = "1.0.71"