[package]
name = "accelerator"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.71"
bzip2 = "0.4.4"
gmod = { version = "17", features = [ "gmcl" ] }
rglua = "2.1.0"
thiserror = "1.0"
toml = "0.8"
ureq = "2.9.1"
